import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import UserWrapper from "@/components/UserWrapper";
import { dark, neobrutalism, shadesOfPurple } from "@clerk/themes";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Mood Sync",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClerkProvider
        
          appearance={{
            baseTheme: [shadesOfPurple,neobrutalism],
            variables: { colorPrimary: "red" },
            signIn: {
              baseTheme: [shadesOfPurple],
              variables: { colorPrimary: "red" },
            },
          }}
        >
          <UserWrapper>{children}</UserWrapper>
        </ClerkProvider>
      </body>
    </html>
  );
}
